---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update repos
      pacman: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
