---
- name: Clone my dotfiles repo
  become_user: jackson
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    force: yes

- name: Clone DT's wallpapers repo
  become_user: jackson
  git:
    repo: "https://gitlab.com/dwt1/wallpapers.git"
    dest: "~/wallpapers"

- name: Check if all the dotfiles are links
  become_user: jackson
  command: "ls -F {{ home_path }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles }}"

- name: Move to backup for dotfiles file that are not links
  become_user: jackson
  command: "mv {{ home_path }}/{{ dotfiles[item.0] }} {{ home_path }}/{{ dotfiles[item.0] }}.bak"
  when: "'@' not in item.1.stdout and item.1.stdout != ''"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Create .local folder for .local/bin link to go into
  become_user: jackson
  command: "mkdir -p {{ home_path }}/.local"

- name: Link dotfiles into home folder
  become_user: jackson
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ home_path }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"
