---
# Getting the main packages from pacman first
- name: Installing required packages
  pacman:
    name:
      - base-devel
      - git
    state: present
  become: true

# Using kewlfft.aur from ansible-galaxy
# Install with `ansible-galaxy collection install kewlfft.aur`
# If it still throws a fit install it from the aur with:
# `paru -S ansible-collection-kewlfft-aur`
- name: Install paru
  become_user: jackson
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present

- name: Install AUR packages
  become_user: jackson
  kewlfft.aur.aur:
    use: paru
    name:
      - bspwm
      - sxhkd
      - awesome-git
      - awesome-freedesktop-git
      - lxappearance
      - papirus-icon-theme
      - arc-gtk-theme
      - rofi
      - picom-jonaburg-git
      - python-pywal
      - nitrogen
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - alacritty
      - ranger
      - nnn
      - mpd
      - mpd-mpris
      - playerctl
      - mpc
      - ncmpcpp
      - nemo
      - neofetch
      - pfetch
      - lolcat
      - nerd-fonts-complete
      - htop
      - bashtop
      - keepassxc
      - yubioath-desktop
      - vim
      - neovim
      - emacs
      - nodejs
      - libreoffice
      - hunspell
      - hunspell-en_us
      - hyphen
      - hyphen-en
      - libmythes
      - mythes-en
      - gimp
      - krita
      - feh
      - brave-bin
      - firefox
      - starship
      - exa-git
      - dust
      - bat
      - xfce4-clipman-plugin
      - mailspring
      - discord-canary
